import type { Localized } from "@brad/domain";
import type { Question, QuestionOption } from "./types";

const o = (id: string, pt: string, en: string): QuestionOption => ({ id, label: { pt, en } });
const t = (pt: string, en: string): Localized => ({ pt, en });

const SDT = "Self-determination theory: autonomy, competence, relatedness (authored question, not the BPNSFS scale)";
const COMB = "COM-B: capability, opportunity, motivation (Michie et al., 2011)";
const MI = "Motivational interviewing: open questions and autonomy support";

/**
 * Initial question bank from the PRD "Brad como secretária da vida", v0.1.
 * Short authored questions inspired by the constructs; none is a validated instrument.
 */
export const QUESTIONS: Question[] = [
  {
    id: "meaning",
    version: 1,
    domain: "any",
    construct: "meaning",
    text: t("O que você quer preservar ou mudar aqui?", "What do you want to keep or change here?"),
    options: [
      o("preserve", "Preservar como está", "Keep it as it is"),
      o("reduce_weight", "Reduzir um peso", "Reduce a burden"),
      o("gain_time", "Ganhar tempo", "Gain time"),
      o("improve_quality", "Melhorar a qualidade", "Improve quality"),
      o("rebuild", "Reconstruir", "Rebuild"),
    ],
    multiple: true,
    followUps: ["reduce_weight", "gain_time", "improve_quality", "rebuild"].map((whenOption) => ({
      whenOption,
      questionId: "improvement",
    })),
    source: MI,
    purpose: t("Entender o significado da área antes de sugerir qualquer coisa.", "Understand what the area means before suggesting anything."),
  },
  {
    id: "improvement",
    version: 1,
    domain: "any",
    construct: "meaning",
    text: t("Como você perceberia uma melhora?", "How would you notice an improvement?"),
    options: [],
    multiple: false,
    source: MI,
    purpose: t("Descrever o sucesso com as palavras da pessoa.", "Describe success in the person's own words."),
  },
  {
    id: "change_desire",
    version: 1,
    domain: "any",
    construct: "change_desire",
    text: t("Existe um desejo real de mudar algo nesta área agora?", "Is there a real wish to change something in this area now?"),
    options: [o("yes", "Sim", "Yes"), o("not_now", "Agora não", "Not now"), o("no", "Não", "No")],
    multiple: false,
    source: MI,
    purpose: t("Nota mediana não é pedido de mudança: perguntar antes de propor.", "A middling score is not a request for change: ask first."),
  },
  {
    id: "preserve",
    version: 1,
    domain: "any",
    construct: "preserve",
    text: t("O que está funcionando aqui e deve ser protegido?", "What is working here and should be protected?"),
    options: [
      o("time", "O tempo que dedico", "The time I give it"),
      o("routine", "Uma rotina", "A routine"),
      o("relationship", "Uma relação", "A relationship"),
      o("quality", "A qualidade atual", "The current quality"),
      o("autonomy", "Minha liberdade de decidir", "My freedom to decide"),
    ],
    multiple: true,
    source: SDT,
    purpose: t("Proteger áreas que vão bem para não serem sacrificadas.", "Protect areas that go well so they are not sacrificed."),
  },
  {
    id: "preserve.family",
    version: 1,
    domain: "family",
    construct: "preserve",
    text: t("Que momento você quer proteger?", "Which moment do you want to protect?"),
    options: [
      o("meal", "Refeição", "Meals"),
      o("outing", "Passeio", "Outings"),
      o("conversation", "Conversa", "Conversation"),
      o("play", "Brincadeira", "Play"),
      o("rest_together", "Descanso conjunto", "Resting together"),
    ],
    multiple: true,
    source: SDT,
    purpose: t("Uma tarefa de outra área não toma esse espaço automaticamente.", "A task from another area does not take this time automatically."),
  },
  {
    id: "autonomy",
    version: 1,
    domain: "any",
    construct: "autonomy",
    text: t("Quanto dessa área depende de decisões suas hoje?", "How much of this area depends on your own decisions today?"),
    options: [
      o("decide", "Posso decidir", "I can decide"),
      o("partly", "Decido em parte", "I decide in part"),
      o("others", "Depende de outras pessoas", "It depends on other people"),
      o("external", "Depende de condições externas", "It depends on external conditions"),
    ],
    multiple: false,
    followUps: [
      { whenOption: "others", questionId: "autonomy.who" },
      { whenOption: "external", questionId: "autonomy.who" },
    ],
    source: SDT,
    purpose: t("Separar o que é escolha da pessoa do que não é.", "Separate what is the person's choice from what is not."),
  },
  {
    id: "autonomy.who",
    version: 1,
    domain: "any",
    construct: "autonomy",
    text: t("De quem ou do quê?", "On whom or on what?"),
    options: [],
    multiple: false,
    source: SDT,
    purpose: t("Nomes só com finalidade e consentimento.", "Names only with a purpose and consent."),
  },
  {
    id: "competence",
    version: 1,
    domain: "any",
    construct: "competence",
    text: t("O que falta para avançar?", "What is missing to move forward?"),
    options: [
      o("information", "Informação", "Information"),
      o("skill", "Habilidade", "Skill"),
      o("clarity", "Clareza", "Clarity"),
      o("support", "Apoio", "Support"),
      o("money", "Dinheiro", "Money"),
      o("time", "Tempo", "Time"),
      o("energy", "Energia", "Energy"),
      o("nothing", "Nada disso", "None of these"),
    ],
    multiple: true,
    source: COMB,
    purpose: t("Distinguir o que pode ser preparado do que é estrutural.", "Tell what can be prepared from what is structural."),
  },
  {
    id: "relatedness",
    version: 1,
    domain: "any",
    construct: "relatedness",
    text: t("Quem ou o que te ajuda nessa área?", "Who or what helps you in this area?"),
    options: [
      o("close_person", "Pessoa próxima", "Someone close"),
      o("professional", "Profissional", "A professional"),
      o("team", "Equipe", "A team"),
      o("community", "Comunidade", "A community"),
      o("nobody", "Ninguém", "Nobody"),
      o("prefer_no_people", "Prefiro não envolver pessoas", "I prefer not to involve people"),
    ],
    multiple: true,
    source: SDT,
    purpose: t("Entender o apoio existente sem pedir dados de terceiros.", "Understand existing support without asking for third-party data."),
  },
  {
    id: "barrier",
    version: 1,
    domain: "any",
    construct: "barrier",
    text: t("Se você quisesse dar um passo pequeno, o que atrapalharia?", "If you wanted to take a small step, what would get in the way?"),
    options: [
      o("tiredness", "Cansaço", "Tiredness"),
      o("overload", "Sobrecarga", "Overload"),
      o("pain", "Dor", "Pain"),
      o("conflict", "Conflito", "Conflict"),
      o("budget", "Orçamento", "Budget"),
      o("indecision", "Falta de decisão", "Indecision"),
      o("environment", "Ambiente", "Environment"),
      o("not_now", "Não quero agir agora", "I don't want to act now"),
    ],
    multiple: true,
    source: COMB,
    purpose: t("Ajustar o contexto antes de cobrar execução.", "Adjust the context before asking for action."),
  },
  {
    id: "barrier.finances",
    version: 1,
    domain: "finances",
    construct: "barrier",
    text: t("Qual é o peso principal agora?", "What weighs the most right now?"),
    options: [
      o("debt", "Dívida", "Debt"),
      o("cash_flow", "Fluxo de caixa", "Cash flow"),
      o("taxes", "Imposto", "Taxes"),
      o("unpredictability", "Imprevisibilidade", "Unpredictability"),
      o("purchases", "Compras", "Purchases"),
    ],
    multiple: true,
    followUps: [{ whenOption: "taxes", questionId: "finances.taxes_help" }],
    source: COMB,
    purpose: t("Não presume acesso bancário nem agenda pagamento.", "Assumes no bank access and schedules no payment."),
  },
  {
    id: "finances.taxes_help",
    version: 1,
    domain: "finances",
    construct: "support",
    text: t("Com impostos, que tipo de ajuda você quer?", "With taxes, what kind of help do you want?"),
    options: [
      o("organise_deadlines", "Organizar vencimentos", "Organise due dates"),
      o("understand_amounts", "Entender valores", "Understand amounts"),
      o("prepare_accountant", "Preparar conversa com contador", "Prepare a conversation with an accountant"),
    ],
    multiple: true,
    source: COMB,
    purpose: t("Escolher a ajuda antes de qualquer ação.", "Choose the help before any action."),
  },
  {
    id: "support",
    version: 1,
    domain: "any",
    construct: "support",
    text: t("Como você quer que eu ajude?", "How do you want me to help?"),
    options: [
      o("remind_when_asked", "Apenas lembrar quando eu pedir", "Only remind me when I ask"),
      o("organise", "Organizar", "Organise"),
      o("show_options", "Mostrar opções", "Show options"),
      o("prepare_draft", "Preparar rascunho", "Prepare a draft"),
      o("ask_before_acting", "Perguntar antes de agir", "Ask before acting"),
      o("do_not_act", "Não atuar", "Do not act"),
    ],
    multiple: true,
    source: SDT,
    purpose: t("Cada capacidade ainda pede uma permissão separada.", "Each capability still needs a separate permission."),
  },
  {
    id: "frequency",
    version: 1,
    domain: "any",
    construct: "frequency",
    text: t("Quando quer rever isso?", "When do you want to review this?"),
    options: [
      o("this_week", "Esta semana", "This week"),
      o("fortnightly", "Quinzenal", "Every two weeks"),
      o("monthly", "Mensal", "Monthly"),
      o("when_i_ask", "Só quando eu pedir", "Only when I ask"),
      o("after_event", "Depois de um evento", "After an event"),
    ],
    multiple: false,
    source: MI,
    purpose: t("Respeitar silêncio e fadiga de perguntas.", "Respect quiet time and question fatigue."),
  },
];

export function getQuestion(id: string): Question | undefined {
  return QUESTIONS.find((q) => q.id === id);
}
